"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
var config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "npx ts-node prisma/seed.ts",
    },
    datasource: {
        // Use DIRECT_URL for migrations and seeds (bypasses pgbouncer)
        url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
    },
});
